version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
        - backend

  backend:
    image: azul/zulu-openjdk:17
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: ./gradlew bootRun -PskipDownload=true
    depends_on:
      - mongodb
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
